apiVersion: v2
name: package-tracker
description: A Helm chart for the package tracker application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - package-tracker
  - logistics
  - shipping
home: https://github.com/jhjaggars/package-tracker
sources:
  - https://github.com/jhjaggars/package-tracker
maintainers:
  - name: jhjaggars
    email: jhjaggars@example.com