apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "package-tracker.labels" . | nindent 4 }}
    {{- with .Values.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}