apiVersion: v1
kind: Secret
metadata:
  name: {{ include "package-tracker.fullname" . }}-secrets
  labels:
    {{- include "package-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- if .adminApiKey }}
  ADMIN_API_KEY: {{ .adminApiKey | b64enc }}
  {{- end }}
  {{- if .uspsApiKey }}
  USPS_API_KEY: {{ .uspsApiKey | b64enc }}
  {{- end }}
  {{- if .upsClientId }}
  UPS_CLIENT_ID: {{ .upsClientId | b64enc }}
  {{- end }}
  {{- if .upsClientSecret }}
  UPS_CLIENT_SECRET: {{ .upsClientSecret | b64enc }}
  {{- end }}
  {{- if .fedexApiKey }}
  FEDEX_API_KEY: {{ .fedexApiKey | b64enc }}
  {{- end }}
  {{- if .fedexSecretKey }}
  FEDEX_SECRET_KEY: {{ .fedexSecretKey | b64enc }}
  {{- end }}
  {{- if .dhlApiKey }}
  DHL_API_KEY: {{ .dhlApiKey | b64enc }}
  {{- end }}
  {{- with .customSecrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.email.enabled }}
  {{- with .Values.email.gmailOauth }}
  {{- if .clientId }}
  GMAIL_CLIENT_ID: {{ .clientId | b64enc }}
  {{- end }}
  {{- if .clientSecret }}
  GMAIL_CLIENT_SECRET: {{ .clientSecret | b64enc }}
  {{- end }}
  {{- if .refreshToken }}
  GMAIL_REFRESH_TOKEN: {{ .refreshToken | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}